name = "serverless-api"
type = "javascript"
zone_id = ""
account_id = "a3e495eaa05a2f834539734867acb774"
route = ""
workers_dev = true
compatibility_date = "2021-11-02"
webpack_config = "webpack.config.js"
kv-namespaces = [
   { binding = "BLOGKV_PROD", id = "f4ed5fe466ff4b02b93bd1a55d13c77b"}
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
