name = "serverless-api"
type = "javascript"
zone_id = ""
account_id = "a3e495eaa05a2f834539734867acb774"
route = ""
workers_dev = true
compatibility_date = "2021-11-02"
webpack_config = "webpack.config.js"
kv_namespaces = [ 
         { binding = "BLOG_KV", id = "d8bc7000252c4832bf9a883eabbe73ba"}
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
